http:
  routers:
    webapp:
      entryPoints:
        - web
      rule: Host(`videoai.localhost`)
      service: webapp

    api:
      entryPoints:
        - web
      rule: Host(`api.videoai.localhost`)
      service: api

    api-on-webapp:
      entryPoints:
        - web
      rule: Host(`videoai.localhost`) && PathPrefix(`/api`)
      middlewares:
        - strip-api-prefix
      priority: 100
      service: api

    render:
      entryPoints:
        - web
      rule: Host(`render.videoai.localhost`)
      service: render

  services:
    webapp:
      loadBalancer:
        servers:
          - url: http://webapp:5173

    api:
      loadBalancer:
        servers:
          - url: http://api:8080

    render:
      loadBalancer:
        servers:
          - url: http://render:8081

  middlewares:
    strip-api-prefix:
      stripPrefix:
        prefixes:
          - /api
